name: New issue for Reproducible Bug
description: "If you're sure it's reproducible and not just your machine: submit an issue so we can investigate."
type: "Bug"
body:
  - type: markdown
    attributes:
      value: We may close your issue without comment if you don't fill out the checklist below and provide ALL requested information (even if you think it's irrelevant). If you won't use the issue template, we may block you from submitting future issues to Homebrew.
  - type: textarea
    attributes:
      render: shell
      label: "`brew doctor` output"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Verification
      description: Verify you've followed these steps. If you can't truthfully check these boxes, open a discussion at https://github.com/orgs/Homebrew/discussions instead. Don't delete these checkboxes or your issue will be closed automatically.
      options:
        - label: I ran `brew update` twice and am still able to reproduce my issue.
          required: true
        - label: I have supplied my `brew doctor` output above and it seems unrelated to my issue.
          required: true
        - label: This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.
          required: true
        - label: I did not use AI/LLM to create this issue, or I disclosed the tool and model used; I will answer maintainer questions myself without AI/LLM.
          required: true
  - type: textarea
    attributes:
      render: shell
      label: "`brew config` output"
    validations:
      required: true
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened (include all command output)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: Step-by-step reproduction instructions (running `brew` commands)
    validations:
      required: true
