name: Commit Style

on:
  pull_request:
    branches: ["**"]
  merge_group:

permissions: {}

jobs:
  check-commit-format:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check commit format
        if: github.event_name == 'pull_request'
        uses: Homebrew/actions/check-commit-format@f8d4222eb633e65c2a0157383cf80861fc7fae7f # 2026.09.07.1
        with:
          check_package_commit_format: false
